### ISSUE TITLE
Forklaring af grafer

### ISSUE THREAD

**Issue by msiebuhr** [brinchj/klima#1]
Jeg formoder at dette repos driver https://brinchj.github.io/ - jeg formoder at graferne er fremskrivning af det _nødvendige_ antal el-bil indregistreringer (og CO₂-nedskæringer, ...), men det står ikke tydeligt på siden.

**Comment by brinchj** [comment]
Tak for kommentaren!

Jeg tror jeg har fået opdateret titlen siden du kiggede, men er ikke sikker på hvad der stod.

Hvis du har forslag til bedre tekst, så tager jeg gerne imod :-) :+1:

**Comment by msiebuhr** [comment]
Det kan jeg heller ikke helt huske - men som jeg lige ser siden, ser den OK ud nu...
